# Derived from https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
# Retries from https://github.com/marketplace/actions/retry-step

name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm ci
    - name: Run Tests (Linux)
      if: runner.os == 'Linux'
      uses: nick-fields/retry@v2.8.1
      with:
        command: xvfb-run -a npm test
        max_attempts: 3
        timeout_minutes: 6
      env:
        TESTING: true
    - name: Run Tests (MacOS/Windows)
      if: runner.os != 'Linux'
      uses: nick-fields/retry@v2.8.1
      with:
        command: npm test
        max_attempts: 3
        timeout_minutes: 6
      env:
        TESTING: true