name: Release

on:
  release:
    types:
    - published
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout/install
      uses: adamhamlin/checkout-node-project@v0.1.0
      with:
        node-version: 16.x

    - name: Publish
      run: npm run deploy -- --pat ${{ secrets.VSCE_PAT }}
